services :
    posgress :
      image : postgres:16
      container_name : postgres_golang_flutter
      restart : always
      environment :
        POSTGRES_USER : postgres
        POSTGRES_PASSWORD : 24434
        POSTGRES_DB : db_golang_flutter
      ports:
       - "5432:5432"
      volumes:
        - postgres_data:/var/lib/postgresql/data

volumes:
    postgres_data:

